== Klassenbeschreibung
=== Topic `+Stammdaten+`
Das Topic `+Stammdaten+` umfasst alle statischen Werte. Darunter fallen z.B. die Aufzählwerte von Listen (INTERLIS-Datentyp «Aufzählung»). Jede Liste wird in einer eigenen Klasse modelliert.

Die Stammdaten werden durch die zuständige Stelle vorgegeben. Bei Bundesthemen ist dies das für die Modellierung zuständige Bundesamt. Bei kantonalen Themen das zuständige kantonale Amt. Die Stammdaten von Bundesthemen können auf der Stufe Kanton erweitert werden. Die kantonalen Erweiterungen werden bei der Überführung ins Bundesmodell den entsprechenden Bundestypen zugeordnet. Bei Bedarf werden die Stammdaten durch die Abteilung Geoinformation nachgeführt und im https://github.com/ch-sz-geo/A256/tree/main/data[data-Verzeichnis] des jeweiligen Themas veröffentlicht.

==== Klasse `+StandardOID_Praefix+`
Die Klasse `+StandardOID_Praefix+` enthält die Präfixe jener Organisationen der kantonalen Verwaltung, für welche eine Standard-OID gelöst wurde.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| OID
| technischer Objektidentifikator
| ceaa37a9-8614-43fc-9a8b-688f95c30218
| öffentlich
m| OID_Praefix
| Präfix-Teil der Standard-OID (siehe https://www.interlis.ch/dokumentation[INTERLIS-Referenzhandbuch])
| ch26dbaj
| öffentlich
m| Bestelldatum
| Tag, an dem das OID-Präfix bestellt wurde.
| 22.01.2026
| öffentlich
m| Organisation
| Name der kantonalen Organisationseinheit, für welche das OID-Präfix bestellt wurde. Als Organisationseinheit gilt in den meisten Fällen das Amt.
| Amt für Umwelt und Energie (AfU)
| öffentlich
m| Thema
| Name des Themas, in welchem die Standard-OID zur Anwendung kommt.
| A254 (Grundwasseraustritte)
| öffentlich
m| Vorname
| Vorname der Person, welche das OID-Präfix bestellt hat.
| Hand
| öffentlich
m| Nachname
| Nachname der Person, welche das OID-Präfix bestellt hat.
| Muster
| öffentlich
m| E_Mail
| E-Mail-Adresse jender Person, welcher das OID-Präfix bestellt hat. Über diese E-Mail-Adresse kann auf der Seite https://www.interlis.ch eine Liste aller von dieser Person bestellten OID-Präfixes ausgegeben werden.
| hans.muster@sz.ch
| öffentlich
m| Bemerkung
| interne Bemerkung für dieses OID-Präfix
| Das ist eine interne Bemerkung.
| +++<span style="color:red;">intern</span>+++
4+| *Bedingungen*
| Eindeutigkeit
3+| Für die Kombination aus "Organisation" und "Thema" wird ein Präfix vergeben.
|===

ifdef::backend-pdf[]
<<<
endif::[]
